apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: boatrec-admin
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: boatrec-admin
  template:
    metadata:
      labels:
        app: boatrec-admin
    spec:
      containers:
      - name: boatrec-admin
        image: mikarinneoracle/boatrec-admin:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 4001
          name: default
      imagePullSecrets:
      - name:  oke-secret
