apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: boatrec-admin
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: boatrec-admin
  template:
    metadata:
      labels:
        app: boatrec-admin
    spec:
      containers:
      - name: boatrec-admin
        image: fra.ocir.io/oracsmnorthuk/boatrec-admin:1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
          name: default
      imagePullSecrets:
      - name:  ocir-secret
